version: 0.1

environment_variables:
  plaintext:
    key: "value"

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - tar -cf ./deployment/package.zip .output/deployment
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - output/package.zip
  discard-paths: yes
